root: true
parser: babel-eslint
extends:
  - plugin:prettier/recommended
env:
  browser: true
  node: true
globals:
  inkdrop: true
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
